import os
env = Environment(ENV = os.environ)

env.Append(LIBS=["png"])
env.Append(CXXFLAGS=["-std=c++11","-g","-Wall","-O3", "-I/usr/local/Cellar/libpng/1.6.28/include"])
env.Append(LINKFLAGS=["-L/usr/local/Cellar/libpng/1.6.28/lib"])

env_nogl = env.Clone()
env_nogl.Append(CXXFLAGS=["-DNO_OPENGL"])

if env['PLATFORM'] == 'darwin':
    env.Append(CXXFLAGS=["-Wno-deprecated-declarations"])
    env.Append(LINKFLAGS=["-framework", "OpenGL", "-framework", "GLUT"])
else:
    env.Append(LIBS=["glut","GL","X11"])


minigl=env.Object("minigl.o","minigl.cpp");
minigl1= env.Object("minigl1.o", "minigl1.cpp");
dump_png=env.Object("dump_png.o","dump_png.cpp");
main=env.Object("main.o","main.cpp");
parse=env.Object("parse.o","parse.cpp");

env.Program("minigl",[main,minigl,parse,dump_png])
env.Program("minigl1",[main,minigl1,parse,dump_png])

main_nogl=env_nogl.Object("main-nogl.o","main.cpp");
parse_nogl=env_nogl.Object("parse-nogl.o","parse.cpp");

env_nogl.Program("minigl-nogl",[main_nogl,minigl,parse_nogl,dump_png])
